runtime: python27
api_version: 1
threadsafe: true
#env: flex
#runtime: custom
#entrypoint: gunicorn -c gunicorn.conf.py index:app
#manual_scaling:
#  instances: 1
#health_check:
#  enable_health_check: False
#env_variables:
#  SQLALCHEMY_DATABASE_URI: >-
#    mysql+pymysql://root:hamlgroup@127.0.0.1:3306/bookxchange
#  SQLALCHEMY_DATABASE_URI: >- 
#    mysql+pymysql://root:hamlgroup@/bookxchange?unix_socket=/cloudsql/bookxchange-cs595:us-central1:bookxchange-cs595
#  BOOKXCHANGE_PROD: true
#beta_settings:
#  cloud_sql_instances: bookxchange-cs595:us-central1:bookxchange-cs595
handlers:
- url: /static
  static_dir: static
- url: .*
  script: index.app

libraries:
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: "2.6"
- name: markupsafe
  version: "0.15"