from handlers.main_handler import MainHandler
from handlers.login_handler import LoginHandler
from handlers.logout_handler import LogoutHandler
from handlers.add_book_handler import AddBookHandler
from handlers.search_handler import SearchHandler
from handlers.auth_handler import AuthHandler
from handlers.attrs_handler import AttrsHandler
from handlers.metadata_handler import MetadataHandler